// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAPI.DbContexts;

namespace UserAPI.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserAPI.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b1eea43-5597-45a6-bdea-e68c60564247"),
                            Name = "Edgar",
                            Password = "123456"
                        },
                        new
                        {
                            Id = new Guid("a052a63d-fa53-44d5-a197-83089818a676"),
                            Name = "Ianko",
                            Password = "123456"
                        },
                        new
                        {
                            Id = new Guid("cb554ed6-8fa7-4b8d-8d90-55cc6a3e0074"),
                            Name = "Fernando",
                            Password = "123456"
                        },
                        new
                        {
                            Id = new Guid("8e2f0a16-4c09-44c7-ba56-8dc62dfd792d"),
                            Name = "Paul",
                            Password = "123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
